name: PHP Project CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Set up .env file
      run: |
        cp .env.example .env
        echo "DB_HOST=localhost" >> .env
        echo "DB_USERNAME=root" >> .env
        echo "DB_PASSWORD=root" >> .env
        echo "DB_DATABASE=onlineshop" >> .env
    - name: Start the server
      run: php -S localhost:8000 -t public &