name: PHP Project CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4' # Change this to the PHP version you need
        extensions: mysqli

    - name: Set up .env file
      run: |
        cp .env.example .env || true
        echo "DB_HOST=localhost" >> .env
        echo "DB_USERNAME=root" >> .env
        echo "DB_PASSWORD=root" >> .env
        echo "DB_DATABASE=onlineshop" >> .env

    - name: Start the PHP server
      run: |
        nohup php -S localhost:8000 -t public > server.log 2>&1 &
        sleep 20 # Increase sleep time to ensure server is ready

    - name: Check PHP server process
      run: ps aux | grep 'php -S'

    - name: Print server logs
      run: cat server.log

    - name: Verify server is running
      run: curl --fail http://localhost:8000 || exit 1
